[project]
name = "devobot"
version = "0.1.0"
description = "A chatbot solution to get answers to FAQs."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.6",
    "langchain>=0.3.14",
    "langchain-openai>=0.2.14",
    "langgraph>=0.2.61",
]

[dependency-groups]
docs = [
    "mkdocs>=1.6.1",
    "mkdocs-material>=9.5.49",
    "mkdocstrings-python>=1.13.0",
    "termynal>=0.12.2",
]
