secrets:
  hosts:  # Host names in [local, azure]
  - name: local
    vaults:
    - name: null
      secrets:
      - name: llm_key  # Secret name in the application (unique)
        value: LLM     # Secret name in the vault
      - name: embeddings_key
        value: EMBEDDINGS
  # - name: azure
  #   vaults:
  #   - name: dvtm-gkenios-uva-dev-kv
  #     secrets:
  #     - name: llm_key  # Secret name in the application
  #       value: LLM     # Secret name in the vault
  #     - name: embeddings_key
  #       value: EMBEDDINGS

models:
  llm:
    api_key: "{{ llm_key }}"  # "{{ <secret> }}" references a secret by name
    api_url: https://openai-devoteam.openai.azure.com/
    api_version: "2024-10-21"  # Optional parameter
    model: gpt-4o-mini
  embeddings:
    api_key: "{{ embeddings_key }}"
    api_url: https://openai-devoteam.openai.azure.com/
    api_version: "2024-10-21" # https://learn.microsoft.com/en-us/azure/ai-services/openai/api-version-deprecation#latest-ga-api-release
    model: text-embedding-ada-002

databases: null
